backend:
  name: git-gateway
  branch: main

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/uploads" # Media files will be stored in the repo under static/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /uploads

collections: # A list of collections the CMS should be able to edit
  - name: "bibliography" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Bibliography Source" # Used in the UI, ie.: "New Post"
    folder: "content/bibliography" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: 'PubType', name: 'pubtype', widget: 'select', options: ['journal', 'proceedings', 'book', 'chapter', 'edited collection'], required: false}
      - {label: "Authors", name: "authors", widget: "string", required: false}
      - {label: "Editors", name: "editors", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Book Title", name: "booktitle", widget: "string", required: false}
      - {label: "Year", name: "year", widget: "string", required: false}
      - {label: "Journal", name: "journal", widget: "string", required: false}
      - {label: "Volume", name: "volume", widget: "string", required: false}
      - {label: "Issue", name: "issue", widget: "string", required: false}
      - {label: "Pages", name: "pages", widget: "string", required: false}
      - {label: "Publisher", name: "publisher", widget: "string", required: false}
      - {label: "External URL", name: "ext_url", widget: "string", required: false}
      - {label: "DOI", name: "doi", widget: "string", required: false}
      - {label: "Annotation", name: "annotation", widget: "markdown", required: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Fields",name: "fields", widget: "list"}
  - name: "projects" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "WROC Projects" # Used in the UI, ie.: "New Post"
    folder: "content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: 'ProjType', name: 'projtype', widget: 'select', options: ['method', 'archival', 'dataviz', 'arts', 'other'], required: true}
      - {label: "Contributors", name: "contributors", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Year", name: "year", widget: "string", required: false}
      - {label: "Organization", name: "organization", widget: "string", required: false}
      - {label: "External URL", name: "ext_url", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "markdown", required: true}
      - {label: Image, name: image, widget: image, required: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Fields",name: "fields", widget: "list"}
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image, required: false}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "content/teaching/_index.md"
        label: "Teaching"
        name: "teaching"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string, required: false}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Body, name: body, widget: markdown}
          - label: Sections
            name: sections
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image, required: false}
      - file: "content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Sections
            name: sections
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
          - label: "4Cs Meetings"
            name: "cccc_meetings"
            widget: list
            folder: "content/cccc_meetings"
            create: true
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image, required: false}
              - {label: "Meeting Agenda", name: "agenda", widget: "file", required: false, assetDir: "uploads/meetings", media_folder: "../uploads/meetings", public_folder: "../uploads/meetings", config: {multiple: false}}
              - {label: "Meeting Notes", name: "notes", widget: "file", required: false, assetDir: "uploads/meetings", media_folder: "../uploads/meetings", public_folder: "../uploads/meetings", config: {multiple: false}}
taxonomies:
  tag: tags
  category: categories
  field: fields